name: CustomOreGen
version: 1.2.42
description: Controls the Ore-Generator
author: Linus122
softdepend: [ASkyBlock, AcidIsland, uSkyBlock]
main: de.Linus122.customoregen.Main
commands:
   customoregen:
     description: reloads the plugin
     usage: /CustomOreGen