name: CustomOreGen
version: 1.1
description: Controls the Ore-Generator
author: Linus122
soft-depends: [ASkyBlock, AcidIsland, uSkyBlock]
main: de.Linus122.customoregen.Main
commands:
   customoregen:
     description: reloads the plugin
     usage: /CustomOreGen